//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 04:33:37 PM CEST 
//


package org.onem2m.xml.protocols;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}acp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}acmp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}ae"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}andi"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}ani"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}bat"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmbf"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmdf"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmdv"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmpv"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cml"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmnr"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmwr"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cmp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cnt"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cin"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}cb"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}dlv"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}dvc"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}dvi"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}evcg"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}evl"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}exin"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}fwr"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}grp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}lcp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}mssp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}mem"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}mgc"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}nod"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sgn"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}pch"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}rbo"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}csr"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}req"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}rqp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}rsp"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sch"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}asar"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}svsn"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}swr"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}stcl"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}stcg"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/>
 *         &lt;/choice>
 *         &lt;element name="uril" type="{http://www.onem2m.org/xml/protocols}listOfURIs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceWrapper", propOrder = {
    "acp",
    "acmp",
    "ae",
    "andi",
    "ani",
    "bat",
    "cmbf",
    "cmdf",
    "cmdv",
    "cmpv",
    "cml",
    "cmnr",
    "cmwr",
    "cmp",
    "cnt",
    "cin",
    "cb",
    "dlv",
    "dvc",
    "dvi",
    "evcg",
    "evl",
    "exin",
    "fwr",
    "grp",
    "lcp",
    "mssp",
    "mem",
    "mgc",
    "nod",
    "sgn",
    "pch",
    "rbo",
    "csr",
    "req",
    "rqp",
    "rsp",
    "sch",
    "asar",
    "svsn",
    "swr",
    "stcl",
    "stcg",
    "sub",
    "uril"
})
public class ResourceWrapper {

    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Acp acp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Acmp acmp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Ae ae;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Andi andi;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Ani ani;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Bat bat;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmbf cmbf;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmdf cmdf;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmdv cmdv;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmpv cmpv;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cml cml;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmnr cmnr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmwr cmwr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cmp cmp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cnt cnt;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cin cin;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Cb cb;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Dlv dlv;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Dvc dvc;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Dvi dvi;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Evcg evcg;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Evl evl;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Exin exin;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Fwr fwr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Grp grp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Lcp lcp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Mssp mssp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Mem mem;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Mgc mgc;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Nod nod;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Notification sgn;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Pch pch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Rbo rbo;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Csr csr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Req req;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Rqp rqp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Rsp rsp;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Sch sch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Asar asar;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Svsn svsn;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Swr swr;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Stcl stcl;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Stcg stcg;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Sub sub;
    @XmlList
    @XmlElement(required = true)
    protected List<String> uril;

    /**
     * Gets the value of the acp property.
     * 
     * @return
     *     possible object is
     *     {@link Acp }
     *     
     */
    public Acp getAcp() {
        return acp;
    }

    /**
     * Sets the value of the acp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acp }
     *     
     */
    public void setAcp(Acp value) {
        this.acp = value;
    }

    /**
     * Gets the value of the acmp property.
     * 
     * @return
     *     possible object is
     *     {@link Acmp }
     *     
     */
    public Acmp getAcmp() {
        return acmp;
    }

    /**
     * Sets the value of the acmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acmp }
     *     
     */
    public void setAcmp(Acmp value) {
        this.acmp = value;
    }

    /**
     * Gets the value of the ae property.
     * 
     * @return
     *     possible object is
     *     {@link Ae }
     *     
     */
    public Ae getAe() {
        return ae;
    }

    /**
     * Sets the value of the ae property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ae }
     *     
     */
    public void setAe(Ae value) {
        this.ae = value;
    }

    /**
     * Gets the value of the andi property.
     * 
     * @return
     *     possible object is
     *     {@link Andi }
     *     
     */
    public Andi getAndi() {
        return andi;
    }

    /**
     * Sets the value of the andi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Andi }
     *     
     */
    public void setAndi(Andi value) {
        this.andi = value;
    }

    /**
     * Gets the value of the ani property.
     * 
     * @return
     *     possible object is
     *     {@link Ani }
     *     
     */
    public Ani getAni() {
        return ani;
    }

    /**
     * Sets the value of the ani property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ani }
     *     
     */
    public void setAni(Ani value) {
        this.ani = value;
    }

    /**
     * Gets the value of the bat property.
     * 
     * @return
     *     possible object is
     *     {@link Bat }
     *     
     */
    public Bat getBat() {
        return bat;
    }

    /**
     * Sets the value of the bat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bat }
     *     
     */
    public void setBat(Bat value) {
        this.bat = value;
    }

    /**
     * Gets the value of the cmbf property.
     * 
     * @return
     *     possible object is
     *     {@link Cmbf }
     *     
     */
    public Cmbf getCmbf() {
        return cmbf;
    }

    /**
     * Sets the value of the cmbf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmbf }
     *     
     */
    public void setCmbf(Cmbf value) {
        this.cmbf = value;
    }

    /**
     * Gets the value of the cmdf property.
     * 
     * @return
     *     possible object is
     *     {@link Cmdf }
     *     
     */
    public Cmdf getCmdf() {
        return cmdf;
    }

    /**
     * Sets the value of the cmdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmdf }
     *     
     */
    public void setCmdf(Cmdf value) {
        this.cmdf = value;
    }

    /**
     * Gets the value of the cmdv property.
     * 
     * @return
     *     possible object is
     *     {@link Cmdv }
     *     
     */
    public Cmdv getCmdv() {
        return cmdv;
    }

    /**
     * Sets the value of the cmdv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmdv }
     *     
     */
    public void setCmdv(Cmdv value) {
        this.cmdv = value;
    }

    /**
     * Gets the value of the cmpv property.
     * 
     * @return
     *     possible object is
     *     {@link Cmpv }
     *     
     */
    public Cmpv getCmpv() {
        return cmpv;
    }

    /**
     * Sets the value of the cmpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmpv }
     *     
     */
    public void setCmpv(Cmpv value) {
        this.cmpv = value;
    }

    /**
     * Gets the value of the cml property.
     * 
     * @return
     *     possible object is
     *     {@link Cml }
     *     
     */
    public Cml getCml() {
        return cml;
    }

    /**
     * Sets the value of the cml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cml }
     *     
     */
    public void setCml(Cml value) {
        this.cml = value;
    }

    /**
     * Gets the value of the cmnr property.
     * 
     * @return
     *     possible object is
     *     {@link Cmnr }
     *     
     */
    public Cmnr getCmnr() {
        return cmnr;
    }

    /**
     * Sets the value of the cmnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmnr }
     *     
     */
    public void setCmnr(Cmnr value) {
        this.cmnr = value;
    }

    /**
     * Gets the value of the cmwr property.
     * 
     * @return
     *     possible object is
     *     {@link Cmwr }
     *     
     */
    public Cmwr getCmwr() {
        return cmwr;
    }

    /**
     * Sets the value of the cmwr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmwr }
     *     
     */
    public void setCmwr(Cmwr value) {
        this.cmwr = value;
    }

    /**
     * Gets the value of the cmp property.
     * 
     * @return
     *     possible object is
     *     {@link Cmp }
     *     
     */
    public Cmp getCmp() {
        return cmp;
    }

    /**
     * Sets the value of the cmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmp }
     *     
     */
    public void setCmp(Cmp value) {
        this.cmp = value;
    }

    /**
     * Gets the value of the cnt property.
     * 
     * @return
     *     possible object is
     *     {@link Cnt }
     *     
     */
    public Cnt getCnt() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cnt }
     *     
     */
    public void setCnt(Cnt value) {
        this.cnt = value;
    }

    /**
     * Gets the value of the cin property.
     * 
     * @return
     *     possible object is
     *     {@link Cin }
     *     
     */
    public Cin getCin() {
        return cin;
    }

    /**
     * Sets the value of the cin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cin }
     *     
     */
    public void setCin(Cin value) {
        this.cin = value;
    }

    /**
     * Gets the value of the cb property.
     * 
     * @return
     *     possible object is
     *     {@link Cb }
     *     
     */
    public Cb getCb() {
        return cb;
    }

    /**
     * Sets the value of the cb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cb }
     *     
     */
    public void setCb(Cb value) {
        this.cb = value;
    }

    /**
     * Gets the value of the dlv property.
     * 
     * @return
     *     possible object is
     *     {@link Dlv }
     *     
     */
    public Dlv getDlv() {
        return dlv;
    }

    /**
     * Sets the value of the dlv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dlv }
     *     
     */
    public void setDlv(Dlv value) {
        this.dlv = value;
    }

    /**
     * Gets the value of the dvc property.
     * 
     * @return
     *     possible object is
     *     {@link Dvc }
     *     
     */
    public Dvc getDvc() {
        return dvc;
    }

    /**
     * Sets the value of the dvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dvc }
     *     
     */
    public void setDvc(Dvc value) {
        this.dvc = value;
    }

    /**
     * Gets the value of the dvi property.
     * 
     * @return
     *     possible object is
     *     {@link Dvi }
     *     
     */
    public Dvi getDvi() {
        return dvi;
    }

    /**
     * Sets the value of the dvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dvi }
     *     
     */
    public void setDvi(Dvi value) {
        this.dvi = value;
    }

    /**
     * Gets the value of the evcg property.
     * 
     * @return
     *     possible object is
     *     {@link Evcg }
     *     
     */
    public Evcg getEvcg() {
        return evcg;
    }

    /**
     * Sets the value of the evcg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Evcg }
     *     
     */
    public void setEvcg(Evcg value) {
        this.evcg = value;
    }

    /**
     * Gets the value of the evl property.
     * 
     * @return
     *     possible object is
     *     {@link Evl }
     *     
     */
    public Evl getEvl() {
        return evl;
    }

    /**
     * Sets the value of the evl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Evl }
     *     
     */
    public void setEvl(Evl value) {
        this.evl = value;
    }

    /**
     * Gets the value of the exin property.
     * 
     * @return
     *     possible object is
     *     {@link Exin }
     *     
     */
    public Exin getExin() {
        return exin;
    }

    /**
     * Sets the value of the exin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exin }
     *     
     */
    public void setExin(Exin value) {
        this.exin = value;
    }

    /**
     * Gets the value of the fwr property.
     * 
     * @return
     *     possible object is
     *     {@link Fwr }
     *     
     */
    public Fwr getFwr() {
        return fwr;
    }

    /**
     * Sets the value of the fwr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fwr }
     *     
     */
    public void setFwr(Fwr value) {
        this.fwr = value;
    }

    /**
     * Gets the value of the grp property.
     * 
     * @return
     *     possible object is
     *     {@link Grp }
     *     
     */
    public Grp getGrp() {
        return grp;
    }

    /**
     * Sets the value of the grp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grp }
     *     
     */
    public void setGrp(Grp value) {
        this.grp = value;
    }

    /**
     * Gets the value of the lcp property.
     * 
     * @return
     *     possible object is
     *     {@link Lcp }
     *     
     */
    public Lcp getLcp() {
        return lcp;
    }

    /**
     * Sets the value of the lcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lcp }
     *     
     */
    public void setLcp(Lcp value) {
        this.lcp = value;
    }

    /**
     * Gets the value of the mssp property.
     * 
     * @return
     *     possible object is
     *     {@link Mssp }
     *     
     */
    public Mssp getMssp() {
        return mssp;
    }

    /**
     * Sets the value of the mssp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mssp }
     *     
     */
    public void setMssp(Mssp value) {
        this.mssp = value;
    }

    /**
     * Gets the value of the mem property.
     * 
     * @return
     *     possible object is
     *     {@link Mem }
     *     
     */
    public Mem getMem() {
        return mem;
    }

    /**
     * Sets the value of the mem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mem }
     *     
     */
    public void setMem(Mem value) {
        this.mem = value;
    }

    /**
     * Gets the value of the mgc property.
     * 
     * @return
     *     possible object is
     *     {@link Mgc }
     *     
     */
    public Mgc getMgc() {
        return mgc;
    }

    /**
     * Sets the value of the mgc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mgc }
     *     
     */
    public void setMgc(Mgc value) {
        this.mgc = value;
    }

    /**
     * Gets the value of the nod property.
     * 
     * @return
     *     possible object is
     *     {@link Nod }
     *     
     */
    public Nod getNod() {
        return nod;
    }

    /**
     * Sets the value of the nod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nod }
     *     
     */
    public void setNod(Nod value) {
        this.nod = value;
    }

    /**
     * Gets the value of the sgn property.
     * 
     * @return
     *     possible object is
     *     {@link Notification }
     *     
     */
    public Notification getSgn() {
        return sgn;
    }

    /**
     * Sets the value of the sgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notification }
     *     
     */
    public void setSgn(Notification value) {
        this.sgn = value;
    }

    /**
     * Gets the value of the pch property.
     * 
     * @return
     *     possible object is
     *     {@link Pch }
     *     
     */
    public Pch getPch() {
        return pch;
    }

    /**
     * Sets the value of the pch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pch }
     *     
     */
    public void setPch(Pch value) {
        this.pch = value;
    }

    /**
     * Gets the value of the rbo property.
     * 
     * @return
     *     possible object is
     *     {@link Rbo }
     *     
     */
    public Rbo getRbo() {
        return rbo;
    }

    /**
     * Sets the value of the rbo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rbo }
     *     
     */
    public void setRbo(Rbo value) {
        this.rbo = value;
    }

    /**
     * Gets the value of the csr property.
     * 
     * @return
     *     possible object is
     *     {@link Csr }
     *     
     */
    public Csr getCsr() {
        return csr;
    }

    /**
     * Sets the value of the csr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Csr }
     *     
     */
    public void setCsr(Csr value) {
        this.csr = value;
    }

    /**
     * Gets the value of the req property.
     * 
     * @return
     *     possible object is
     *     {@link Req }
     *     
     */
    public Req getReq() {
        return req;
    }

    /**
     * Sets the value of the req property.
     * 
     * @param value
     *     allowed object is
     *     {@link Req }
     *     
     */
    public void setReq(Req value) {
        this.req = value;
    }

    /**
     * Gets the value of the rqp property.
     * 
     * @return
     *     possible object is
     *     {@link Rqp }
     *     
     */
    public Rqp getRqp() {
        return rqp;
    }

    /**
     * Sets the value of the rqp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rqp }
     *     
     */
    public void setRqp(Rqp value) {
        this.rqp = value;
    }

    /**
     * Gets the value of the rsp property.
     * 
     * @return
     *     possible object is
     *     {@link Rsp }
     *     
     */
    public Rsp getRsp() {
        return rsp;
    }

    /**
     * Sets the value of the rsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rsp }
     *     
     */
    public void setRsp(Rsp value) {
        this.rsp = value;
    }

    /**
     * Gets the value of the sch property.
     * 
     * @return
     *     possible object is
     *     {@link Sch }
     *     
     */
    public Sch getSch() {
        return sch;
    }

    /**
     * Sets the value of the sch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sch }
     *     
     */
    public void setSch(Sch value) {
        this.sch = value;
    }

    /**
     * Gets the value of the asar property.
     * 
     * @return
     *     possible object is
     *     {@link Asar }
     *     
     */
    public Asar getAsar() {
        return asar;
    }

    /**
     * Sets the value of the asar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asar }
     *     
     */
    public void setAsar(Asar value) {
        this.asar = value;
    }

    /**
     * Gets the value of the svsn property.
     * 
     * @return
     *     possible object is
     *     {@link Svsn }
     *     
     */
    public Svsn getSvsn() {
        return svsn;
    }

    /**
     * Sets the value of the svsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Svsn }
     *     
     */
    public void setSvsn(Svsn value) {
        this.svsn = value;
    }

    /**
     * Gets the value of the swr property.
     * 
     * @return
     *     possible object is
     *     {@link Swr }
     *     
     */
    public Swr getSwr() {
        return swr;
    }

    /**
     * Sets the value of the swr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Swr }
     *     
     */
    public void setSwr(Swr value) {
        this.swr = value;
    }

    /**
     * Gets the value of the stcl property.
     * 
     * @return
     *     possible object is
     *     {@link Stcl }
     *     
     */
    public Stcl getStcl() {
        return stcl;
    }

    /**
     * Sets the value of the stcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stcl }
     *     
     */
    public void setStcl(Stcl value) {
        this.stcl = value;
    }

    /**
     * Gets the value of the stcg property.
     * 
     * @return
     *     possible object is
     *     {@link Stcg }
     *     
     */
    public Stcg getStcg() {
        return stcg;
    }

    /**
     * Sets the value of the stcg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stcg }
     *     
     */
    public void setStcg(Stcg value) {
        this.stcg = value;
    }

    /**
     * Gets the value of the sub property.
     * 
     * @return
     *     possible object is
     *     {@link Sub }
     *     
     */
    public Sub getSub() {
        return sub;
    }

    /**
     * Sets the value of the sub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sub }
     *     
     */
    public void setSub(Sub value) {
        this.sub = value;
    }

    /**
     * Gets the value of the uril property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uril property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUril().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUril() {
        if (uril == null) {
            uril = new ArrayList<String>();
        }
        return this.uril;
    }

}
